### ISSUE TITLE
Lab 2: Set Covering  with GA Algorithm- Peer Review by Marco Pratticò (s294815)

### ISSUE THREAD

**Issue by marcopra** [fracapuano/CompIntelligence_2022#2]
# Lab 2: Set Covering  with GA Algorithm- Peer Review by Marco Pratticò (s294815)

Hi, I am Marco Pratticò (s294815) and this is my Peer Review.

# Overview

The code is well-written and well-organized. I appreciate the use of classes with exhaustive comments and docs. The plots reported are really useful for seeing when the algorithm saturates.

## Issues

* In this algorithm, you are accepting non-valid solutions when generating the offspring. The evaluation of non-valid solutions occurs similarly to the valid ones. I think (I tested it but I am not 100% sure) that the algorithm can get stuck on a non-valid candidate with a better fitness value, instead of accepting a valid solution. For example with N = 3, we suppose we I have two candidates: `[[1], [2]]` and `[[1,2,3]]` that we call respectively `candidate1` and `candidate2`. We can compute their fitness, according to your definition, using `w_coverage * covering_fitness + w_reps * reps_fitness) - w_reps` with `w_coverage = 0.2` and `w_reps = -0.8` (without considering the normalization). For `candidate1` we obtain 0.2x2 - 0.8x2 - (-0.8) = -0.4, while for `candidate2` we obtain 0.2x3 - 0.8x3 - (-0.8) = -1. Since you are using a sorting function with `reverse = True`, in the first position of the sorted list we will find `candidate1`. So, doing `fittest.append(self.population[0]` - as in your code - you will consider a non-valid solution, instead of considering the optimal solution.

* A problem related to the previous point is that there is the possibility to find a non-valid solution and discarding other valid solutions. For example, for N = 20 and n_generations = 10 you will provide a non-valid solution at the end, while other valid solutions are discarded (I checked this part).
 
## Suggestions

To solve this issue you can act in two ways:

* accepting just the valid offspring, but there is the possibility that you discard almost optimal solutions.
* accepting the non-valid offspring and adding a penalty to them. Please pay attention that acceptance with penalties reduces the risk of this issue but doesn't completely avoid it (I think).

From the graph, we can note that after a certain number of generations the algorithm saturates. The number of "useful" generations changes accordingly with the size of the problem. You can create - empirically - a mathematical function $N_{Gen} = f(N)$ to set the right number of "useful" generations.

**Comment by fracapuano** [comment]
Hi there, thank you very much for your feedback. 

> The code is well-written and well-organized. I appreciate the use of classes with exhaustive comments and docs. The plots reported are really useful for seeing when the algorithm saturates.

Thanks for that, we coded bearing in mind that someone else was supposed to read our code, hence our commitment to clarity. 

> In this algorithm, you are accepting non-valid solutions when generating the offspring [...]

We discussed a lot about this last point and arrived to the conclusion that we wanted to develop a solution as general as possible, in order to try as much as possible to use the *feasibility* as a driving signal for the evolution process, rather than forcing it top-down. We believe this is the best approach indeed, since it allows the evolution process to exploit information about feasibility (our fitness function depends on that, albeit marginally with respect to weight) while not being constrained. We observed that only valid solutions are generated in the end of the process. However, we see you definitely have a point... I honestly believe this is just a matter of interpretation. 

> For example with N = 3, we suppose we I have two candidates: [[1], [2]] and [[1,2,3]] that [...]

We appreciate you did take the time to carefully go over our code, to the point to try to reproduce it on your own. However, discarding the normalisation affects the value of the fitness function, that is thought to be in the 0-1 range.
I tried to see if you had a point in your example, but for seed the prof. told us to use (`seed=42`) the problem is not solvable for `N=3`. However, we would highly appreciate your contribution in this matter, so please feel free to fork the repo and issue a PR if you feel. We all are very busy, but we would be pleased if you would want to collaborate to further investigate this matter. 

>  For example, for N = 20 and n_generations = 10 you will provide a non-valid solution at the end [...]

Using an approach that embeds feasibility in the fitness function, clearly creates the condition to obtain non valid solutions at the end. Probably we should consider changing the feasibility weight so to adapt them in a way that feasibility is more strongly enforced. 

> accepting the non-valid offspring and adding a penalty to them. Please pay attention that acceptance with penalties reduces the risk of this issue but doesn't completely avoid it [...]

That is exactly what we have been doing! 

> The number of "useful" generations changes accordingly with the size of the problem. You can create [...]

I am curious on how you would create such a function. If you want to dig deep in the math (like expected number of generations before convergence to really good/optimal fitness values), I would love too! I would model the problem using the Markov Property, even though I would say that *previous steps* (i.e., further in time than $t-1$) definitely have an influence on the evolution. I am desperately trying to find the time to study Levy processes. This looks like a good application. Let me know if you want to collaborate on this topic. 

All in all, thanks for the careful and throughout review. I am closing this issue, but feel free to re-open should you feel the need to add anything. Grazie!
